### ISSUE TITLE
Change contributor schedule (or disable GitHub webhook)

### ISSUE THREAD

**Issue by FiniteReality** [novelrt/get-novelrt-contributors#2]
We should probably change the schedule of this to be once a day, or at the very least change the notification settings such that we don't get notifications for this repo.

It's not super workflow breaking, but I definitely did use that channel to keep track of issues and stuff being opened and updated and it's a little harder when it's spammed with auto-update pushes. :sweat_smile:

**Comment by RubyNova** [comment]
Agreed, its kind of a lot.

**Comment by FiniteReality** [comment]
Additional thoughts that would require a little more effort:
- Add a workflow trigger to NovelRT repos we want to track to trigger a workflow on (https://docs.github.com/en/rest/repos/repos#create-a-repository-dispatch-event)
- Said workflow pulls the current list of contributors and commits to gh-pages branch
- Code then just uses that as an asset as if it were normal

**Comment by capnkenny** [comment]
This was completed to be once a day previously.
